version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi_dev
    volumes:
      - db-volume-dev:/var/lib/postgresql/data

  api:
    image: joaoagrilo/ac2:dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: papi_dev
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8585:8585"
    depends_on:
      - database

volumes:
  db-volume-dev:
