version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi_prod
    volumes:
      - db-volume-prod:/var/lib/postgresql/data

  api:
    image: joaoagrilo/ac2:prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: papi_prod
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8585"
    depends_on:
      - database

volumes:
  db-volume-prod:
