version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: joaoagrilo/ac2:staging 
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: papi
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8485:8585" 
    depends_on:
      - database

volumes:
  db-volume:
