version: '3'

services:
  database:
    image: postgres
    container_name: prod-database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prod_db
    volumes:
      - db-prod-volume:/var/lib/postgresql/data

  api:
    image: joaoagrilo/ac2:prod
    container_name: prod-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: prod_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8083:8080"
    depends_on:
      - database

volumes:
  db-prod-volume:
