version: '3'

services:
  database:
    image: postgres
    container_name: dev-database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    volumes:
      - db-dev-volume:/var/lib/postgresql/data

  api:
    image: joaoagrilo/ac2:dev
    container_name: dev-api
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: dev_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8081:8080"
    depends_on:
      - database

volumes:
  db-dev-volume:
